Update readme with suggestions from tech writer
nobl9/nobl9-action pull request #5
Opened 2022-05-31 22:08 UTC by quan-nobl9

Grammatical changes

2022-06-01 16:53 UTC, a-hales approved these changes

2022-06-09 05:07 UTC, ian-bartholomew requested changes

2022-06-09 05:07 UTC, ian-bartholomew commented on README.md
> +### `CLIENT_SECRET`
should be lower cased

2022-06-09 05:07 UTC, ian-bartholomew commented on README.md
> +### `CLIENT_ID`
should be lower cased

2022-06-09 05:07 UTC, ian-bartholomew commented on README.md
> +This action applies a Nobl9 configuration file (specified via the SLOCTL_YAML input parameter) to a project using the `sloctl` (https://docs.nobl9.com/sloctl-user-guide/) tool.
`SLOCTL_YAML` should be lower cased

2022-06-09 05:07 UTC, ian-bartholomew commented on README.md
> +### `ACCESS_TOKEN`
should be lower cased

2022-06-09 05:07 UTC, ian-bartholomew commented on README.md
> +### `PROJECT`
should be lower cased

2022-06-09 05:07 UTC, ian-bartholomew commented on README.md
> +### `SLOCTL_YAML`
should be lower cased

2022-06-14 01:58 UTC, quan-nobl9 reviewed
reverting back to lowercase

2022-12-08 20:58 UTC, ian-bartholomew approved these changes

2022-12-08 20:58 UTC, merged