Update to include newest sloctl features
nobl9/nobl9-action pull request #8
Opened 2023-03-27 14:48 UTC by greg-agacinski

2023-03-27 14:53 UTC, nieomylnieja requested changes

2023-03-27 14:53 UTC, nieomylnieja commented on README.md
> +      - uses: nobl9/nobl9-action@v0.2.1
```suggestion
      - uses: nobl9/nobl9-action@v0.2.2
```

2023-03-27 14:53 UTC, nieomylnieja commented on entrypoint.sh
> +  -y # default to auto confirm
Let's maybe leave some context here:

```suggestion
  -y # Required to auto confirm, for more details refer to: https://docs.nobl9.com/sloctl-user-guide?_highlight=prompt&_highlight=threshold#apply
```

2023-03-27 14:53 UTC, nieomylnieja commented on README.md
> +| `dry_run` | The path or glob pattern to the configuration in YAML format, relative to the root directory of the repository | No | `false` |
Wrong description ;)

2023-03-27 15:04 UTC, greg-agacinski commented on README.md
> +| `dry_run` | The path or glob pattern to the configuration in YAML format, relative to the root directory of the repository | No | `false` |
```suggestion
| `dry_run` | Submits server-side request without persisting the configured resources | No | `false` |
```

2023-03-27 15:09 UTC, nieomylnieja approved these changes, later dismissed
lgtm, didn't test it though

2023-03-28 11:36 UTC, nieomylnieja approved these changes

2023-03-28 14:02 UTC, merged